export const PROBLEMS_CONTENT = {
  title: 'בנק שאלות',
  subtitle: (count) => `${count}+ שאלות בנושאי קידוד נפוצים בראיונות`,
  searchPlaceholder: 'חיפוש שאלה...',
  filters: {
    topicAll: 'כל הנושאים',
    difficultyAll: 'כל הרמות',
    statusAll: 'כל הסטטוסים',
    difficulty: {
      easy: 'קל',
      medium: 'בינוני',
      hard: 'קשה',
    },
    status: {
      completed: 'הושלם',
      failed: 'לא עבר',
      inProgress: 'בתהליך',
      notStarted: 'לא התחיל',
    },
  },
  tableHeaders: {
    status: 'סטטוס',
    question: 'שאלה',
    topic: 'נושא',
    level: 'רמה',
    acceptance: 'אחוז הצלחה',
    companies: 'חברות',
    publish: 'פרסום',
  },
  publish: {
    on: 'מפורסם',
    off: 'טיוטה',
    saving: 'שומר...',
    success: 'סטטוס הפרסום עודכן',
    error: 'עדכון הפרסום נכשל',
  },
  admin: {
    addButton: 'הוסף שאלה',
    editAction: 'עריכה',
    deleteAction: 'מחיקה',
    actionsHeader: 'ניהול',
    deleteConfirm: (title) => `למחוק את השאלה "${title}"? פעולה זו אינה הפיכה.`,
    deleteSuccess: 'השאלה נמחקה',
    deleteError: 'מחיקת השאלה נכשלה',
    createSuccess: 'השאלה נוצרה',
    updateSuccess: 'השאלה עודכנה',
  },
  form: {
    createTitle: 'שאלה חדשה',
    editTitle: 'עריכת שאלה',
    fields: {
      id: 'מזהה (מספר)',
      title: 'כותרת (אנגלית)',
      titleHe: 'כותרת (עברית)',
      topic: 'נושא',
      difficulty: 'רמת קושי',
      functionName: 'שם הפונקציה',
      companies: 'חברות (מופרד בפסיקים)',
      descriptionHe: 'תיאור (עברית)',
      constraints: 'אילוצים (שורה לכל אילוץ)',
      hints: 'רמזים (שורה לכל רמז)',
      starterCode: 'קוד התחלתי (Python)',
      examples: 'דוגמאות (JSON)',
      testCases: 'מקרי בדיקה (JSON)',
      published: 'מפורסם למשתמשים',
    },
    difficulty: { easy: 'קל', medium: 'בינוני', hard: 'קשה' },
    save: 'שמירה',
    saving: 'שומר...',
    cancel: 'ביטול',
    required: 'שדות חובה: מזהה, כותרת באנגלית, כותרת בעברית',
    invalidExamples: 'שדה הדוגמאות חייב להיות מערך JSON תקין',
    invalidTestCases: 'שדה מקרי הבדיקה חייב להיות מערך JSON תקין',
    examplesHint: '[{"input":"...","output":"...","explanation":"..."}]',
    testCasesHint: '[{"inputs":[...],"expected":...,"label":"..."}]',
  },
};
