export const SIMULATION_CONTENT = {
  headerBadge: 'סימולציית ראיון עבודה',
  title: 'ראיון טכני מדומה',
  subtitle: '3 שאלות אקראיות · 45 דקות · פתור כמה שיותר',
  timeLeft: 'זמן שנותר',
  startInterview: 'התחל ראיון',
  timeUp: '⏰ הזמן נגמר!',
  solvedSummary: (solved, total) => `פתרת ${solved} מתוך ${total} שאלות`,
  completedCounter: (solved, total) => `${solved}/${total} הושלמו`,
  newInterview: 'ראיון חדש',
  questionLabel: (idx) => `שאלה ${idx + 1}`,
  solvedBadge: 'הושלם',
  attemptedBadge: 'נוסה',
  solveFirst: 'התחל את הראיון תחילה',
  solveAgain: 'פתור שוב',
  solveQuestion: 'פתור שאלה',
  perfect: '🎉 מושלם! פתרת את כולן!',
  goodEffort: 'כל הכבוד על המאמץ!',
  solvedCountText: (solved, total) => `פתרת ${solved} מתוך ${total} שאלות`,
  timerDoneTitle: 'הזמן נגמר!',
  difficultyLabel: {
    easy: 'קל',
    medium: 'בינוני',
    hard: 'קשה',
  },
};
